[package]
name = "http-client"
version = "0.1.0"
description = "A desktop HTTP client built with GPUI."
authors = ["suxiaoshao <48886207+suxiaoshao@users.noreply.github.com>"]
license = "MIT"
repository = "https://github.com/suxiaoshao/gpui"
homepage = "https://github.com/suxiaoshao/gpui"
edition = "2024"

[package.metadata.bundle]
name = "HTTP Client"
identifier = "top.sushao.http-client"
publisher = "CN=Sushao"
short_description = "A desktop HTTP client built with GPUI."
long_description = """
HTTP Client is a GPUI-based desktop application for composing and inspecting
HTTP requests.
"""
category = "DeveloperTool"

[package.metadata.bundle.deb]
depends = ["libasound2"]

[dependencies]
http-client-request.workspace = true
http-client-response.workspace = true
app-i18n.workspace = true
gpui-kit = { workspace = true, features = [
  "tree-sitter-languages",
] }
gpui-tokio.workspace = true

thiserror = "2.0.21"

# log
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["local-time"] }
dirs-next = "2.0.0"

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
