app-title = HTTP Client

gpui-form-error-required = This field is required.

button-send = Send
button-add = Add
button-confirm = Confirm
button-delete = Delete
button-select-file = Select File
button-change-file = Change File
button-clear-file = Clear File
button-move-up = Move Up
button-move-down = Move Down

field-method = Method
field-url = URL
field-name = Name
field-key = Key
field-value = Value
field-content-type = Content Type
field-file = File
field-username = Username
field-password = Password
field-token = Token
field-location = Location
field-timeout-ms = Timeout (ms)

tab-params = Params
tab-authorization = Authorization
tab-headers = Headers
tab-body = Body
tab-settings = Settings

params-invalid-url-disabled = Enter a valid absolute HTTP or HTTPS URL to edit query parameters.

body-none = None
body-form-data = form-data
body-urlencoded = x-www-form-urlencoded
body-text = Text
body-binary = binary

text-format-plain = Plain Text
text-format-json = JSON
text-format-javascript = JavaScript
text-format-html = HTML
text-format-xml = XML
text-format-css = CSS

multipart-text = Text
multipart-file = File
multipart-file-not-selected = No file selected

auth-none = No Auth
auth-basic = Basic Auth
auth-bearer = Bearer Token
auth-api-key = API Key
auth-location-header = Header
auth-location-query = Query Params
auth-generated-override = Generated authorization takes precedence over conflicting request values.
auth-query-override = API Key authorization overrides the query parameter named “{ $name }”.
body-content-type-override = This explicit header takes precedence over the Content-Type generated by Body.

settings-follow-redirects = Follow redirects
settings-follow-original-method = Preserve the original method when following redirects
settings-timeout-help = Set to 0 for no timeout.

request-url-invalid = Enter a valid absolute URL with a host.
request-url-scheme-invalid = Only HTTP and HTTPS URLs are supported.
request-header-name-invalid = Enter a valid HTTP header name.
request-header-value-invalid = Enter a valid HTTP header value.
request-media-type-invalid = Enter a valid media type.
request-multipart-name-required = Enter a name for this multipart part.
request-multipart-name-invalid = Multipart names cannot contain line breaks or null characters.
request-file-required = Select a file.
request-file-unavailable = The selected file is unavailable, unreadable, or not a regular file.
request-file-name-invalid = File names must not be empty or contain line breaks or null characters.
request-basic-username-colon = Basic Auth usernames cannot contain a colon.
request-auth-value-invalid = Enter a value that can be used in an HTTP authorization header.
request-api-key-name-required = Enter an API key name.
request-api-key-name-invalid = Enter a valid API key name for the selected location.
