[package]
name = "platform-ext"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.21"
tracing = "0.1.44"

[target.'cfg(target_os="macos")'.dependencies]
block2 = "0.6.2"
objc2 = "0.6.4"
objc2-app-kit = "0.3.2"
objc2-user-notifications = "0.3.2"
objc2-core-graphics = { version = "0.3.2", features = [
  "CGDirectDisplay",
  "CGGeometry",
  "CGEvent",
  "CGEventSource",
  "CGEventTypes",
  "CGRemoteOperation",
  "CGWindow",
] }
objc2-foundation = { version = "0.3.2", features = [
  "block2",
  "NSArray",
  "NSDictionary",
  "NSObject",
  "NSUserDefaults",
  "NSString",
] }

[target.'cfg(target_os="windows")'.dependencies]
windows = { version = "0.62.2", features = [
  "Foundation",
  "UI_ViewManagement",
  "Win32_Graphics_Gdi",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Input_KeyboardAndMouse",
] }
windows-core = "0.62.2"
