[package]
name = "gpui-form"
version = "0.1.0"
edition = "2024"

[features]
default = []
garde-adapter = ["dep:garde"]

[dependencies]
garde = { workspace = true, optional = true }
gpui = { workspace = true }
gpui-form-macros = { workspace = true }
gpui-operation = { workspace = true }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
gpui-component = { workspace = true }
gpui-form-gpui-component = { workspace = true }
trybuild = "1.0.120"
